---
# defaults file for rsyslog

# rsyslong.conf.j2 variables
rsyslog_udp_server: true
rsyslog_udp_server_port: 514
rsyslog_tcp_server: false
rsyslog_tcp_server_port: 514

# 50-default.conf.j2 variables
# Custom log templates and destinations
rsyslog_custom_rules:
  - $template DynFile,"/var/log/%HOSTNAME%/system.log"
  - "*.* ?DynFile"

# Relays
relay_logs: []
destination_server:
...
