---
# tasks file for getweather
- name: build the getweather container
  docker_image:
    build:
      path: /vagrant/getweather/
      pull: no # force pull updated image
    name: getweather
    tag: "1.0"
    source: build # build - build from Dockerfile,
                  # load - load from .tar
                  # pull - pull from registry
                  # local - just use existing image
  tags:
  - getweather
...
