---
# tasks file for docker
- name: install docker packages
  apt:
    name:
      - docker.io
      - python-docker
    state: present
    
- name: enable docker startup on boot
  service:
    name: docker
    enabled: yes
    
- name: set up docker daemon (logging driver)
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify: restart docker
...
