---
- name: pan-net
  hosts: localhost
  gather_facts: false # we don't use facts in playbooks/roles; speedup run a little bit
  # exercise 1
  roles:
    - roles/rsyslog
    - roles/docker
    - roles/getweather

  tasks:
    # exercise 2
    - name: install NMAP
      apt:
        name:
          - nmap
        state: present
...
