---
# tasks file for rsyslog
- name: configure rsyslog.conf and custom rules
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ item.path }}{{ item.src }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_items:
  - { src: rsyslog.conf, path: /etc/ }
  - { src: 50-default.conf, path: /etc/rsyslog.d/ }
  notify:
  - restart rsyslog
...
